Gemfile, spec/features/visitors/event_page_spec.rb, spec/features/visitors/home_page_spec.rb, spec/support/sunspot.rb
Where
====
Original PR: https://github.com/AyuntamientoMadrid/agendas/pull/1 it was automagitcally closed but some force push to remove files (secrets.yml) that should ever have been present on the git history of this repo. My apologies to anyone else that could have had problems because of it (but you should have cleaned up it before me)
What
====
Developers should not have remember to run solr locally to be able to pass specs.
How
====
Installing sunspot_rails_tester gem to be able to fake solr on testing evironment.
Allow to run solr implicitly on specs with :search metadata defined.
Example:
```
scenario 'visit search by keyword and area result page', :search do
@event = FactoryGirl.create(:event, title: 'New event from Capybara')
visit root_path
fill_in :keyword, with: 'Capybara' …
```
=> Sunspot testing config by @senen

app/models/event.rb
Where & What
=====
Trying out README's instruction to run `rake generator:initialize` or the `rake db:test_seed` task results in a crash:
```
NoMethodError: undefined method `get_title' for nil:NilClass
/Users/bertocq/work/consul/dev/agendas/app/models/event.rb:5:in `block in <class:Event>'
/Users/bertocq/work/consul/dev/agendas/db/test_seeds.rb:35:in `<top (required)>'
/Users/bertocq/work/consul/dev/agendas/lib/tasks/db.rake:4:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:test_seed
(See full trace by running task with --trace)
```
Because of the usage of [public_activity](https://github.com/chaps-io/public_activity) gem, very very badly (assuming there will be always a controller involved in the creation of a Event object) at …
=> Fix Event creation from console

.rubocop_todo.yml, Gemfile, app/models/category.rb, app/models/interest.rb, app/models/organization.rb, db/migrate/20171122161940_add_new_fields_to_organizations.rb, db/schema.rb, spec/factories/organizations.rb, spec/models/organization_spec.rb
Where
=====
* **Related Issue:** #52 
What
====
We need to create some new fields at Organizations table to be able to store some remote CSV information
These new fields are:
* inscription_reference:string
This is the unique identifier for associations and federations at CSV files, so we will need to use this   field on daily updates at importation process. 
* inscription_date:date (Maybe src dates will be well formatted 🙏 )
This is the inscription date of association or federation. I colud be useful on importation update record process.
* entity_type: enum [:association | :federation]
* neighbourhood: string (Only for imported associations)
* district: string (Only for imported associations)
* scope: string
* associations_count:integer (Only for imported associations)
* members_count: …
=> Add new fields to organizations

Gemfile.lock
Where
=====
* **Related PR's:** #43
What
====
This reverts commit 296a57f5d65a77d1ed16cea4611f21f02bfd335f, reversing
changes made to f618db3010007cab8c8ec10d91aeeeebb7834686.
This update breaks public events index locally and we do not have time to check and to solve problems with newest version! 
How
===
Reverting depfu PR
Warnings
=======
We have to merge very carefully depfu updates because we dont have enough specs to rely on.
=> Revert sunspot solr update.

app/controllers/admin/organizations_controller.rb, app/helpers/admin/organizations_helper.rb, app/models/ability.rb, app/views/admin/organizations/index.html.erb, app/views/layouts/_admin_sidebar.html.erb, config/locales/admin.en.yml, config/locales/admin.es.yml, config/routes.rb, spec/features/admin/organizations_spec.rb
Where
=====
* **Related Issue:** #28 
What
====
Add organizations index (views and controllers) for admins.
How
===
- Create the corresponding controller (with actions) and views.
- Add a link to the admins sidebar to access the index.
- Added CanCanCan abilites to avoid non-admin users access that page.
Screenshots
===========
Test
====
Added test for organizations index.
Deployment
==========
Nothing to apply.
Warnings
========
Nothing to apply.
=> Admin organizations index

app/assets/stylesheets/all.css.scss, app/views/layouts/_header.html.erb, config/locales/public.es.yml
Where
=====
* **Related Issue:** #18  
In this first version actual home should have a few links to allow users to access other important public pages.In next versión we will create a welcome#home page with links to many other pages. See #27 to check @agileontheweb first proposal.
Add links to access the "Agendas públicas" and the "Consulta del registro".
**Desktop**
**Tablet**
**Smartphone**
**Smartphone menu**
=> Home add new buttons

db/seeds.rb, db/test_seeds.rb, lib/tasks/organizations.rake
Where
=====
* **Related Issue:** #73
What
====
Create seeds to insert organization interests into DB.
How
===
I created seeds for fresh installs and a rake task for the production website, like in #80.
Screenshots
===========
There aren't.
Test
====
Not needed.
Deployment
==========
run rake task: ` rake organizations:add_organization_interests` in order to insert the categories.
Warnings
========
Nothing to apply.
=> Organization interests seed

app/controllers/organizations_controller.rb, app/helpers/application_helper.rb, app/views/organizations/index.csv.erb, app/views/organizations/index.html.erb, app/views/visitors/index.html.erb, spec/features/organizations_spec.rb
Where
=====
* **Related Issue:** #37
* **Related PR:** #74 
What
====
Allo any user to exportation organizations index results.
How
===
Adding new link "Export"
Generating organizations CSV file with new index.csv.erb view and using PublicOrganizationExport class.
Screenshots
=========
=> Add export link to organizations index

app/controllers/users_controller.rb, app/models/user.rb, app/views/users/_form.html.erb, config/locales/activerecord.es.yml, config/locales/admin.es.yml, spec/features/admin/passwords_specs.rb
Where
=====
* **Related Issue:** #33
What
====
* Allow admins to reset an user's password
How
===
* Modified related MVCs accordingly to allow the new feature
* Refactored related spec to make it more DRY
Screenshots
===========
Test
====
* Increased coverage for three (3) scenarios
=> Allow admins to reset other users's passwords

app/models/ability.rb, app/models/event.rb, db/migrate/20171128143359_add_status_to_events.rb, db/schema.rb, spec/features/admin/events_spec.rb, spec/models/event_spec.rb
Where
=====
* **Related Issue:** #19
What
====
Let the organization users create new events with status on_request
How
===
- Add a column to the events table called status.
- The status is given with a `before_create` callback, so that each time an event is created, no matter the place, the status is set if the user is from an organization.
- Enable the permissions for organization users to create events in 'ability.rb'.
Screenshots
===========
Test
====
- Test for the organizations feature (access to events index and create new event).
- Test for the `before_create` callback (set the status for the event).
Deployment
==========
Run migrations.
Warnings
========
Nothing.
=> Organization user event new

app/models/event.rb, db/migrate/20171204113941_change_event_status_type.rb, db/schema.rb, spec/models/event_spec.rb
Where
=====
* **Related Issue:** #115 
* **Related PR's:** #95 
What
====
Fix the enum problem that was not merge in the previous PR.
How
===
Changed the column type string to integer and added an enum to set the status.
Screenshots
===========
There aren't.
Test
====
The test to check the status after create has been updated with the new enum.
Deployment
==========
There is a new migration to change the column.
Warnings
========
Nothing.
=> Event field status to enum

app/models/ability.rb, spec/features/admin/events_spec.rb
Where
=====
* **Related Issue:** #49 
What
====
Allow organization users to edit events that are on request.
How
===
Adding permissions to the lobby users to enable the `edit` and `update` methods if the event's status is "requested".
Screenshots
===========
Test
====
Tests added to check that the organization users can only edit events on request.
Deployment
==========
Nothing.
Warnings
========
Nothing.
=> Organization user can edit events on request

app/controllers/organizations_controller.rb, app/models/interest.rb, app/models/organization.rb, app/views/organizations/_search_form.html.erb, spec/features/organizations_spec.rb
Where
=====
* **Related Issue:** #112
What
====
* Organizations can now be filtered by interests
How
===
* Modified related MVCs to fulfill the new requirement
* Refactored Organizations sorting spec to improve DRYness
Screenshots
===========
* Left sidebar with the new filter
* Shown results when an user filters Organizations by a certain interest
Test
====
* Increased coverage for the sole scenario generated by this new feature
=> Allow filtering of Organizations by interests

app/views/admin/organizations/_data.html.erb, db/migrate/20171210174630_add_display_field_to_categories.rb, db/schema.rb, db/test_seeds.rb, lib/public_organization_importer.rb, lib/tasks/organizations.rake, spec/factories/categories.rb
Where
=====
* **Related Issue:** #124 
Only display categories by default.
When import Organizations (Federations and Associations) from csv, we need create categories with a flag display: false, this categories not display on new organization page.
Test
====
- None
Deployment
==========
- As usual
Warnings
========
- None
=> Only display default categories on organization#new

app/controllers/organizations_controller.rb, app/models/organization.rb, app/views/organizations/_search_form.html.erb, spec/features/organizations_spec.rb
Where
=====
* **Related Issue:** #15 
* **Related PR's:** #94
We have 3 entity_types from Organizations. Only need display on public organization index the organizations as lobby. 
*Note: entity_type: [:association, :federation, :lobby]
- Render only organizations on public page with entity_type: :lobby
- Remove filter on public page that allow filter by :association, :federation, :lobby because now only display Organizations as lobby.
Test
====
- Fix specs.
Deployment
==========
- As usual.
Warnings
========
- None
=> Remove filter by entity type. Only display organizations with entity :lobby

app/controllers/organizations_controller.rb, app/models/organization.rb, app/views/organizations/_search_form.html.erb, spec/features/organizations_spec.rb
Where
=====
* **Related Issue:** #138
What
====
* Allow users to filter Organizations by category
How
===
* Modified related MVCs to allow the new filter to work as expected
Screenshots
===========
Test
====
* Increased test coverage for the only scenario the new feature creates
=> Allow filtering of Organizations by category

app/models/event.rb, config/locales/en.yml, config/locales/es.yml, lib/events_exporter.rb, lib/tasks/export.rake, spec/events_exporter_spec.rb, spec/lib/tasks/export_rake_spec.rb
Where
=====
* **Related Issue:** #106 
What
====
Generation of a file that contains the lobby informations and the events. This files must be accessible in a public URL.
How
===
- Generate the exporter to build the .csv, .xls and the .json files.
- Create a rake task to save this files in the public/export/filename.ext
Screenshots
===========
There aren't.
Test
====
Specs to test the exporter and the new rake task.
Deployment
==========
In order to generate the files, the rake task should be run.
Warnings
========
Nothing to apply.
=> Url lobby organizations events

bin/rails, bin/rake, bin/rspec, bin/spring
Where
=====
* **Related PR's:** #40, #48 
What
====
* Update Rails binaries to solve deprecation warning when starting `rails server`
How
===
* Modified `rails`, `rake`, `rspec` and `spring` binaries based on a personal, up-to-date Rails project
=> Fix deprecation warning when 'rails server' is started

app/assets/javascripts/events.js.erb, app/models/concerns/event_agent_existence_validator.rb, app/models/event.rb, app/views/events/index.html.erb, config/locales/admin.en.yml, config/locales/admin.es.yml, spec/factories/events.rb, spec/features/admin/events_spec.rb, spec/features/visitors/event_page_spec.rb
Where
=====
* **Related Issue:** https://github.com/AyuntamientoMadrid/agendas/issues/121
What
====
- Add validation to event. Now requires at least 1 EventAgent if lobby_activity is set to true
How
===
- Added validation in model and updated jquery validator for events/_form.html.erb (events.js.erb)
Screenshots
===========
Test
====
- Changed tests because now lobby_event requires EventAgent and it stops fitting in the definition of some of them
=> add validation by Agents to lobby event

app/assets/javascripts/events.js.erb, app/assets/stylesheets/all.css.scss, app/controllers/events_controller.rb, app/helpers/admin/events_helper.rb, app/models/event.rb, app/models/organization.rb, app/models/user.rb, app/views/events/_form.html.erb, app/views/events/_search_form.html.erb, app/views/events/index.html.erb, app/views/layouts/_admin_sidebar.html.erb, app/views/organizations/index.html.erb, config/locales/admin.en.yml, config/locales/admin.es.yml, db/migrate/20171207122529_add_organization_id_to_events.rb, db/schema.rb, spec/factories/events.rb, spec/features/admin/events_spec.rb, spec/models/event_spec.rb
Where
=====
* **Related Issue:** #51 
What
====
Add a new filter by status.
How
===
- Put a Select with multiple option in the view of the index of Event. 
-Changes the method for event searches , with one with multiple params.
-Add a field "organization_id" to event in the schema
Screenshots
===========
Test
====
Add the test and fixed some test with the new way of search.
Warnings
====
There are some test with conflicts.
=> Issue 51 manager and organization user event index

Gemfile, Gemfile.lock, app/assets/javascripts/events.js.erb, app/controllers/events_controller.rb, app/helpers/application_helper.rb, app/mailers/event_mailer.rb, app/models/event.rb, app/views/event_mailer/decline.erb, app/views/events/_form.html.erb, config/environments/development.rb, config/locales/admin.en.yml, config/locales/admin.es.yml, config/locales/mailers.en.yml, config/locales/mailers.es.yml, db/migrate/20171213141703_add_declinded_to_event.rb, db/schema.rb, spec/features/admin/events_spec.rb, spec/features/mailers/events_mailer_spec.rb, spec/spec_helper.rb
Where
=====
* **Related Issue:** https://github.com/AyuntamientoMadrid/agendas/issues/133
What
====
- Add decline to events 
- Add setup for mail testing
- Add gem for check mails on development
How
===
- How you implemented/achieved the objective ?
Screenshots
===========
Test
====
- I have increased the tests to cover the new features and aditionally added more test for cancel event mail
=> Manage user can set status event

app/views/organizations/show.html.erb, config/locales/organizations.en.yml, config/locales/organizations.es.yml, spec/features/organizations_spec.rb
Where
=====
* **Related Issue:** https://github.com/AyuntamientoMadrid/agendas/issues/151
What
====
- Add links to owned events from organization_show
Screenshots
===========
=> add owned events to organizations show

app/controllers/positions_controller.rb, app/helpers/admin/events_helper.rb, app/models/event.rb, app/models/position.rb, app/views/events/_form.html.erb, config/locales/admin.en.yml, config/locales/admin.es.yml, config/routes.rb, spec/features/admin/events_spec.rb
Where
=====
* **Related Issue:** #131 
What
====
- Autocomplete option for Lobby user in Holder selection
How
===
- Implement an autocomplete field
Screenshots
===========
Test
====
Fixed test to use the new search option
=> Autocomplete option for Lobby user in Events section Holders

lib/tasks/events.rake
Where
=====
* **Related Issue:** #166 
What
====
- We need to update the status of events to :done when they have occurred.
How
===
- Create a rake task to update event status from :accepted to :done when "scheduled" is less or equal to today.
Screenshots
===========
- None
Test
====
- Add specs for rake task  events:update_event_status
Deployment
==========
- A usual.
Warnings
========
- Need add this rake task on cron job related #170
=> Add rake task for update event status to done

app/models/event.rb, app/views/visitors/show.html.erb, spec/features/visitors/event_page_spec.rb
Where
=====
* **Related Issue:** #192 
When search on visitors#index by "titular de agenda" the results include events that "titular de agenda" have participated as "asistente titular de agenda"
How
===
- Add to Event searcher new results by participants 
Screenshots
===========
- None
Test
====
- Add missing specs.
Deployment
==========
- As usual
Warnings
========
- None
=> Search events

app/controllers/admin_controller.rb, app/controllers/events_controller.rb, app/controllers/uweb_access_controller.rb, app/helpers/admin/sidebar_helper.rb, app/views/events/_form.html.erb, app/views/events/edit.html.erb, app/views/events/new.html.erb, app/views/events/show.html.erb, app/views/layouts/_admin_sidebar.html.erb, config/locales/admin.en.yml, config/locales/admin.es.yml, spec/features/admin/events_spec.rb
Where
=====
* **Related Issue:** https://github.com/AyuntamientoMadrid/agendas/issues/181
What
====
- Add 2 links to the user (:user) menu, shortcuts for filtered events
Screenshots
===========
=> add filters for events in the user menu

Gemfile.lock, app/controllers/admin/organizations_controller.rb, app/controllers/organizations_controller.rb, app/controllers/users/registrations_controller.rb, app/controllers/users/sessions_controller.rb, app/helpers/organizations_helper.rb, app/models/organization.rb, app/models/user.rb, app/views/admin/organizations/_agents_fields.html.erb, app/views/organizations/show.html.erb, config/routes.rb, spec/features/admin/organizations_spec.rb, spec/features/organizations_spec.rb, spec/features/users/sign_in_spec.rb
What
====
- Avoid user soft delete sign in
- Display organizations invalid or canceled on index. 
- Only can search by agents when invalidate eq false and not canceled. 
- When organization is canceled or invalidate can display his show page but without agents.
- When organization is canceled or invalidate an user admin can display his show page with agents.
Screenshots
===========
- None
Test
====
- Add missing specs
Deployment
==========
- As usual
Warnings
========
- None
=> Check lobby

Gemfile.lock
What
====
Solve potential security vulnerability of current 'yard' gem version. 
'yard' gem is a 'jazz_hands' gem dependency.
How
===
Update yard to fix CVE-2017-17042 vulnerability on 0.8.7.6 version
```
bundle lock --update yard
```
Screenshots
===========
=> Update yard to fix CVE-2017-17042 vulnerability on 0.8.7.6 version

app/controllers/admin/organizations_controller.rb, app/helpers/admin/organizations_helper.rb, app/models/attachment.rb, app/models/organization.rb, app/views/admin/organizations/_attachment_fields.html.erb, app/views/admin/organizations/_attachments.html.erb, app/views/admin/organizations/_form.html.erb, app/views/admin/organizations/index.html.erb, config/locales/organizations.es.yml, db/migrate/20171226135403_add_organization_id_to_attachments.rb, db/schema.rb, spec/features/admin/organizations_spec.rb
Where
=====
* **Related Issue:** #216 
What
====
Allow organizations to have many attachments.
How
===
Adding foreign key to attachment model called :organization_id.
Adding nested attachment fields to organization form.
Screenshots
===========
Test
====
Test coverage increased to grant nested attachments behaviour.
Deployment
==========
As usual
Warnings
========
None
=> Add attachments to organizations

lib/tasks/organizations.rake
Where
=====
* **Related Issue:** #221 
What
====
- Add values for Registered lobbies.
How
===
- Create a rake task to import all registered lobbies.
Screenshots
===========
- None
Test
====
- None
Deployment
==========
- Execute rake organizations:add_registered_lobbies
Warnings
========
- None
=> Add new rake task add_registered_lobbies

lib/tasks/events.rake
Where
=====
* **Related PR's:** #222 
What
====
Old events should have a value [true|false] to pass model validations.
Update old version events setting lobby_activity to false.
=> Set lobby_activity to false on old events update task.

app/controllers/admin/organizations_controller.rb, spec/features/admin/organizations_spec.rb, spec/mailers/user_mailer_spec.rb
Where
=====
* **Related Issue:** #237 
When create organization need send mail to user organization with his account and his password.
Send welcome user mailer to new user when create organization.
Screenshots
===========
- None
Test
====
- Add mailer specs. Add count mailer when create organization.
Deployment
==========
- As usual.
Warnings
========
- None
=> Add welcome email when create organization. Add specs

app/helpers/organizations_helper.rb, app/views/events/_event_represented_entities.html.erb
What
====
- Generates internal json calls for autocomplete using the https protocol
Why
===
- The autocomplete when creating an event was throwing a Mixed Content exception, as the page is loaded with https but this url was making an http call
How
===
- Using the protocol param for url generation
Screenshots
===========
- Internal json call using https
Test
====
- Not needed
Deployment
==========
- As usual
Warnings
========
- None
=> Fix url generation for https

app/views/events/show.html.erb
Where
=====
* **Related Issue:** #255 
What
====
Render attachment description only when is present on user show page.
Description attribute from event attachments is not mandatory so we cannot apply always html_safe.
How
===
Adding simple condition!
=> Render event attachment description only when is present

config/initializers/devise.rb, spec/features/users/passwords_spec.rb, spec/features/users/sessions_spec.rb, spec/rails_helper.rb
Where
=====
* **Related Issue:** #304
What
====
Fix devise mailer configuration. 
How
===
Changing mailer_sender email at devise initializer.
Screenshots
===========
Not needed
Test
====
None
Deployment
==========
As usual
Warnings
========
None
=> Change default sender for Devise Mailer

app/controllers/visitors_controller.rb, app/helpers/application_helper.rb, app/views/visitors/headline/_holder.html.erb, config/locales/activerecord.en.yml, config/locales/activerecord.es.yml, spec/features/visitors/event_page_spec.rb
Where
=====
* **Related Issue:** #321, #311
What
====
Redirect request to agendas action to visitors index when given holder does not exist
How
===
Controlling holder existence at agenda action and redirecting when holder is not found.
Screenshots
===========
Not needed
Test
====
Added specs to check redirection behavior
Deployment
==========
As usual
Warnings
========
None
=> Redirect to visitors index when holder not found on agenda action

public/404.html, public/422.html, public/500.html
Where
=====
* **Related Issue:** #312
What
====
Fix 404, 500 and 422 pages background renderization.
How
===
Fixing CSS background image source definition.
Screenshots
===========
Not needed
Test
====
Nothing added
Deployment
==========
As usual
Warnings
========
None
=> Fix background styles definition on error pages

app/assets/javascripts/events.js.erb, app/controllers/organizations_controller.rb, app/views/events/_form.html.erb, spec/features/admin/events_spec.rb
What
====
- Allow manager/admin user create an event to association/federation as lobby
How
===
- Hide and disable validations from Agents and RepresentedEntities when organizations selected is an associations/federation.
Screenshots
===========
- None
Test
====
- Add and fix specs.
Deployment
==========
- As usual
Warnings
========
- None
=> Allow manager/admin user create an event to association/federation as lobby

app/controllers/admin/organizations_controller.rb, app/models/user.rb, spec/features/admin/organizations_spec.rb
Where
=====
* **Related Issue:** #320 (This PR closes #320 once merged)
What
====
* Fixed a `NoMethodError` exception when soft deleting an organization
How
===
* `soft_delete` User method exposed as public
* Guard clause added to `Admin::Organizations` controller to avoid raising an exception if the organization does not have an user associated
Test
====
* Increased coverage
=> Fix for `NoMethodError` exception when soft-deleting an organization

.travis.yml, config/sunspot.yml.example
Where
=====
* **Related Issue:** #345 
What
====
After merging #345 Travis started to fail because he wasn't able to find Solr.
How
===
Travis does not need to copy sunspot.yml.example file to be able to run specs, this was the problem indeed. Before mergin #345, sunspot.yml.example wasn't exist so Travis was able to generate his own configuration, after mergin #345, sunspot.yml was copied form exmaple file Travis started to fail because hi was not able to find solr with this configuration.
To solve this we have removed this copy from config directory so Travis use his own.
Screenshots
===========
Not needed
Test
====
Same
Deployment
==========
None
Warnings
========
None
=> Travis sunspot config

config/deploy.rb
Where
=====
* **Related PR's:** #346 , #74 
What
====
export.rake tasks generated files on public/export folder. This folder should be shared between releases. Now, after every deploy public/export folder is lost between releases.
How
===
Adding public/export folder to capistrano deploy linked directories.
Screenshots
===========
Not needed
Test
====
Same
Deployment
==========
As usual
Warnings
========
None
=> Add public/export folder to capistrano linked dirs

app/controllers/application_controller.rb, spec/features/application_spec.rb
Where
=====
* **Related Issue:** #310 
What
====
- Display an error with a invalid authenticity token 
Instructions
- Sign in
- Edit or create an event 
- Open a second tab
- Sign out in the second tab
- Return to the first tab and save the event
How
===
- Write a test that covers the bug 
- Added the method to handle the invalid token and redirect to sign in
- The test passed with the new method.
Test
====
- Added the test to verify that the error of a 'AuthenticityToken'
=> Handle InvalidAuthenticityToken exception

app/views/organizations/index.html.erb, spec/features/organizations_spec.rb
What
====
Customer want changes on generated lobbies.csv files. Changes are not defined yet. In the meantime we deactivate this feature until changes are defined.
How
===
Commented link code and skipping related specs.
Screenshots
===========
Not needed
Test
====
Related specs skipped
Deployment
==========
As usual
Warnings
========
None
=> Deactivate organizations public page export link

app/views/admin/organizations/_attachment_fields.html.erb, app/views/admin/organizations/show.html.erb, spec/features/admin/organizations_spec.rb
Where
=====
* **Related Issue:** #377 
What
====
- We want display organization attachments on organization page for admins.
- We want display organization attachment name on edit organization page.
Screenshots
===========
Admin organization page:
Admin edit organization page:
Test
====
- Add specs.
Deployment
==========
- As usual
Warnings
========
- None
=> Edit lobby

app/views/admin/users/index.csv.erb, spec/features/admin/users_spec.rb
Where
=====
* **Related Issue:** #372 
What
====
After moving users controller to admin namespace and because there were not written specs for this feature, we broke this feature without knowledge.
How
===
Using new route helpers on export feature.
Screenshots
===========
Without UI changes.
Test
====
New specs were added to check this feature.
Deployment
==========
As usual
Warnings
========
None
=> Add specs to admin/users#index for :csv formatted request

app/models/user.rb, spec/models/user_spec.rb
Where
=====
* **Related Issue:** #374 
What
====
- When import uweb process we set always password for all users.
How
===
- Only set new password when create new user. If user exists not set password
Screenshots
===========
- None
Test
====
- Add specs
Deployment
==========
- As usual.
Warnings
========
- None
=> Not set password when user exists. Add missing specs

app/models/event.rb, spec/features/admin/events_spec.rb, spec/models/event_spec.rb
Where
=====
* **Related Issue:** #392 #394 
What
====
- Avoid create event as lobby activity without organization
How
===
- Add validate on event model.
Screenshots
===========
- None
Test
====
- Add feature and model spec
Deployment
==========
- As usual
Warnings
========
- None
=> Add validate organization on create events with lobby activity
