AyuntamientoMadrid/agendas

- config/secrets.yml.example
Where
=====
* **Related Issue:** https://github.com/AyuntamientoMadrid/agendas/issues/6
What
====
- Erased sensible data from file secrets.yml.example
How
===
- N/A
Screenshots
===========
- N/A
Test
====
- N/A
Deployment
==========
- Any details to remember when this feature is deployed?
Remember to use a correct secrets.yml :)
Warnings
========
- N/A
> erased sensible data

- config/secrets.yml.example
Where
=====
* **Related Issue:** #24
What
====
Allow travis to run specs normally
How
===
Adding secret_key_base entry for test environment to secrets.yml.example
Screenshots
===========
N/A
Test
====
N/A
Deployment
==========
N/A
Warnings
========
None
> Travis: Test secret key base

- db/migrate/20171122183612_add_approach_to_organizations.rb
- db/schema.rb
Where
=====
* **Related Issue:** #13#
What
====
Add missing field to organizations for federations and assocations importation process.
Deployment
==========
As usual.
Warnings
========
As usual.
> Add approach to organizations

- config/locales/admin.en.yml
- config/locales/admin.es.yml
What
====
- Fix locale user role :lobby
Screenshots
===========
Deployment
==========
- As usual
Warnings
========
- None
> Add missing locale

- spec/features/admin/organizations_spec.rb
What
====
Eliminate features specs with unnecessary js on admin organization.
Deployment
==========
- As usual.
Warnings
========
- None
> Readjusted spec.

- app/assets/javascripts/events.js.erb
- app/controllers/admin/organizations_controller.rb
- app/controllers/agents_controller.rb
- app/controllers/events_controller.rb
- app/controllers/organizations_controller.rb
- app/controllers/represented_entities_controller.rb
- app/helpers/organizations_helper.rb
- app/models/event.rb
- app/models/user.rb
- app/views/events/_event_agent_fields.html.erb
- app/views/events/_form.html.erb
- app/views/events/index.html.erb
- config/locales/admin.en.yml
- config/locales/admin.es.yml
- config/routes.rb
- db/migrate/20171202235742_add_lobby_scheduled_to_events.rb
- db/migrate/20171203204027_add_general_remarks_to_events.rb
- db/schema.rb
- db/test_seeds.rb
- spec/features/admin/events_spec.rb
- spec/features/admin/organizations_spec.rb
- spec/features/organizations_spec.rb
- spec/models/attachment_spec.rb
- spec/support/helpers.rb
- spec/support/helpers/js_helpers.rb
Where
=====
* **Related Issue:** #103 
What
====
An "Organization User" can create a new event.
How
===
- Add fields to the current form to create a event:
- general remarks
- proposal lobby scheduled
- Add js to fill organization name by default
- Hidden fields to the current form:
- Published at
- Scheduled
Screenshots
===========
Test
====
- Add some missing spec.
- Add specs for validate create a new event by organization user.
Deployment
==========
- New migrations. We need execute rake db:migrate
Warnings
========
The styles have yet to be revised by @agileontheweb . But since I want to make a upload to the test server, I will merge it and create a specific issue for this review. #109
> Lobby new event

- app/assets/stylesheets/all.css.scss
- app/views/admin/organizations/_admin_search_form.html.erb
- app/views/admin/organizations/_agents_fields.html.erb
- app/views/admin/organizations/_data.html.erb
- app/views/admin/organizations/_interests.html.erb
- app/views/admin/organizations/_legal_representant_fields.html.erb
- app/views/admin/organizations/_lobby_data.html.erb
- app/views/admin/organizations/_represented_entities_fields.html.erb
- app/views/admin/organizations/_user_fields.html.erb
- app/views/admin/organizations/index.html.erb
- app/views/admin/organizations/new.html.erb
- app/views/events/_form.html.erb
- app/views/events/edit.html.erb
- app/views/events/new.html.erb
- config/locales/admin.es.yml
- config/locales/organizations.en.yml
- config/locales/organizations.es.yml
- spec/features/admin/organizations_spec.rb
What
====
Some css, translation and enumeration improvements
How
===
Add new translates. Add new css.
Screenshots
===========
- If changes affect UI just show them drag&dropping images here
Test
====
Fix specs resulting from rebase with master
Deployment
==========
As usual
Warnings
========
None
> New organization select enums

- app/views/events/_form.html.erb
- config/locales/organizations.en.yml
- config/locales/organizations.es.yml
Where
=====
* **Related Issue:** #108 
What
====
We have uploaded a version for the client to see and have improved the form display.
There are some texts that do not correctly explain the functionality
How
===
- Improve form styles.
- Improve translations to clarify functionality and fix translates.
Screenshots
===========
- Translates
- Styles
Test
====
- No need
Deployment
==========
- As usual
Warnings
========
- None
> Improve form styles. Improve and fix translates.

- app/assets/javascripts/admin/admin.js
- app/assets/javascripts/events.js.erb
- app/views/admin/organizations/_data.html.erb
- app/views/admin/questions/_form.html.erb
- app/views/events/_form.html.erb
- app/views/events/index.html.erb
- config/locales/admin.en.yml
- config/locales/admin.es.yml
Where
=====
New event.
What
====
Some mini fixes. 
How
===
Change some style.
Added translation "pending"
Initialize tinymce via js. Remove tag rails tinymce :language => I18n.local.
Screenshots
===========
- No needed
Test
====
- Manual  Ok.
Deployment
==========
Warnings
========
> Event list pending

- app/assets/stylesheets/all.css.scss
Where
=====
New event.
What
====
- Add max height and max width to Input organization 
How
===
- Add css
Screenshots
===========
Test
====
- No needed
Deployment
==========
- Nothing
Warnings
========
- Nothing
> Autocomplete with max height and max width.

- app/assets/javascripts/events.js.erb
- app/views/events/_form.html.erb
Where
=====
New event
What
====
In the form we have  - It is a meeting where Lobby activity will be done? 
If yes and exist only one name, autoset option into select.
How
===
- Simple js
Screenshots
===========
Test
====
- Manual
Deployment
==========
Warnings
========
> New event: Select option if exist only one organization.

- app/helpers/organizations_helper.rb
- app/views/organizations/index.html.erb
- config/locales/organizations.es.yml
- spec/features/organizations_spec.rb
Where
=====
#148
What
====
Change  "Consulta del registro de Organizaciones" with "Consulta del registro de lobbies
Change "Últimas Organizaciones registradas" with "Incorporaciones más recientes" only when entering. Remove the text once the filter is used.
How
===
Changed yml.
On submit check if params :interests exist hide text."
Screenshots
===========
#148
Test
====
- Is manual. Tested passed.
Deployment
==========
Warnings
========
> Change titles 

- app/views/organizations/show.html.erb
Where
=====
Show organization
What
====
- Change font size in the accordion interests
How
===
- Added tag "< p >" in the interests accordion 
Screenshots
===========
Test
====
Deployment
==========
Warnings
========
> Changed font size into accordion interests

- app/controllers/organizations_controller.rb
- app/models/agent.rb
- app/models/organization.rb
- app/views/organizations/_search_form.html.erb
- config/locales/public.en.yml
- config/locales/public.es.yml
- spec/features/organizations_spec.rb
- spec/models/agent_spec.rb
Where
=====
* **Related Issue:** #135 
What
====
Add a new search criteria by agents of active organizations.
How
===
- Added the new searchable criteria to the organizations model.
- Added the dropdown to the form.
- Added a new scope to get the active organizations.
Screenshots
===========
UPDATED
Test
====
- Feature spec added to test the new search form.
- Spec added to test the new organizations scope.
Deployment
==========
Nothing to apply.
Warnings
========
Nothing to apply.
> Public organization search by agents

- app/controllers/static_pages_controller.rb
- config/routes.rb
Where
=====
* **Related Issue:** #34
What
====
* Create general static pages
How
===
* Created the necessary controller and views
* Modified `routes.rb` accordingly for the pages
Notes & warnings
========
* The information necessary to populate the static pages hasn't been provided by the client so the views files are empty
* Since we're also waiting for the client to approve the mockups, the URLs to access the pages are not available from the UI
> Create general static pages

- app/assets/stylesheets/all.css.scss
- app/controllers/organizations_controller.rb
- app/views/organizations/show.html.erb
- db/migrate/20171213171029_add_default_value_to_subvention_and_contract.rb
- db/schema.rb
Where
=====
Nothing to comment
What
====
- Organizations show: If it is an administrator the page breaks.
How
===
- Check if current_user.try(:admin?), if admin remove validate.
Screenshots
===========
Test
====
- Manual test. Passed
Deployment
==========
Warnings
========
> General fix

- app/controllers/admin/organizations_controller.rb
- app/controllers/organizations_controller.rb
- app/models/organization.rb
- db/test_seeds.rb
- lib/public_organization_importer.rb
- spec/lib/tasks/db_rake_spec.rb
What
====
- Wrong filter by default (entity_type: :lobby)
How
===
- Add new filter on solr by enums
- Remove scopes to method search from solr
Test
====
- None.
Deployment
==========
- As usual
Warnings
========
- None
> Fix sorl search by enums

- app/assets/stylesheets/all.css.scss
- app/controllers/events_controller.rb
- app/views/events/_form.html.erb
- app/views/events/show.html.erb
- app/views/layouts/_admin_sidebar.html.erb
- app/views/layouts/_footer.html.erb
- app/views/visitors/show.html.erb
- config/locales/admin.en.yml
- config/locales/admin.es.yml
What
====
Change style in the show event.
Aligned icon event list.
Changed text in the sidebar "gestion de lobby o Administracion"
How
===
- Html
Test
====
- Manual test passed
Deployment
==========
Warnings
========
> New style show events

- app/assets/stylesheets/all.css.scss
- app/controllers/organizations_controller.rb
- app/helpers/application_helper.rb
- app/views/organizations/_organization.html.erb
- app/views/organizations/_search_form.html.erb
- app/views/organizations/index.html.erb
- app/views/visitors/index.html.erb
- config/locales/public.es.yml
- db/test_seeds.rb
- spec/features/organizations_spec.rb
What
====
- New layout lobby list
How
===
- Filters online line
- Added style
- Change button "cancelar" with "Limpiar"
- List min 20 lobby
- Pagination in the top and the bottom
- If there are no meetings  not show the text
- Responsive
Screenshots
===========
Test
====
- Manual test passed
Deployment
==========
Warnings
========
> New layout lobby list

- app/views/visitors/index.html.erb
- config/locales/public.es.yml
Where
=====
#178 
What
====
- Change title with Agendas públicas
How
===
- public.es.yml
Screenshots
===========
Test
====
- Is manual  and passed
Deployment
==========
Warnings
========
> Changed text.

- app/assets/stylesheets/all.css.scss
- app/views/events/_form.html.erb
- config/locales/admin.es.yml
- spec/features/admin/events_spec.rb
What
====
- Add button "Salir sin grabar"
- Changed style button reason activity
- Fix spec
How
===
- html
- css
Screenshots
===========
Test
====
- Manual passed
Deployment
==========
Warnings
========
> Changed style buttons. Added button exit without save. Fix spec.

- Gemfile
- Gemfile.lock
What
====
Remove ruby version from Gemfile
> Remove ruby version from Gemfiles

- app/assets/stylesheets/all.css.scss
- app/controllers/organizations_controller.rb
- app/helpers/organizations_helper.rb
- app/views/shared/_search_keywords.html.erb
- app/views/visitors/index.html.erb
- config/locales/organizations.es.yml
Where
=====
- Organizations
- Agends
What
====
-  Organizations: Changed style to the search text
-  Organizations: Changed text on change the selector
- Agents: Add margin to title
How
===
- html , css
Screenshots
===========
Test
====
- Manual test: Passed
Deployment
==========
- Manual test: Passed
Warnings
========
- Manual test: Passed
> Some design fixed

- app/assets/stylesheets/all.css.scss
- app/controllers/organizations_controller.rb
- app/views/admin/organizations/_lobby_data.html.erb
- app/views/admin/organizations/_represented_entities_fields.html.erb
- app/views/admin/organizations/show.html.erb
- app/views/events/show.html.erb
- app/views/organizations/_organization.html.erb
- app/views/organizations/index.html.erb
- app/views/organizations/show.html.erb
- app/views/visitors/_event.html.erb
- app/views/visitors/index.html.erb
- config/locales/admin.es.yml
- config/locales/organizations.es.yml
- config/locales/public.es.yml
- spec/features/organizations_spec.rb
What
====
- Changed style from: Organization show, registration lobby, Visitors,
- Added word "Sleccionar" in the selector
- Small font size 
- Decrease padding and margin in the list of registration lobby
- Change size and width in the order selector
- Number_field only positive value
- Show number of meeting 
- When enter in the lists of organizations and when click on clear button show the most recent 
How
===
- Html, css
Screenshots
===========
Test
====
-Test manual passed
Deployment
==========
Warnings
========
> Change some style design

- app/helpers/application_helper.rb
- app/views/activities/index.html.erb
- app/views/admin/organizations/show.html.erb
- app/views/events/_form.html.erb
- app/views/events/index.html.erb
- app/views/events/show.html.erb
- app/views/holders/_position_fields.html.erb
- app/views/organizations/show.html.erb
- app/views/visitors/index.csv.erb
- spec/features/admin/events_spec.rb
- spec/features/organizations_spec.rb
Where
=====
* **Related Issue:** #193 
What
====
Event page is showing wrong scheduled at time. More precisely is showing 1 hour more!
How
===
Using rails **I18n to** render dates and times.
Screenshots
===========
Not needed
Test
====
Same
Deployment
==========
As usual
Warnings
========
None
> Use I18n to render dates and datetimes

- config/deploy.rb
What
====
Update deploy configuration file for capistrano to be able to make deploys from this version.
How
===
Changing github repository url.
> Update capistrano deploy configuration file

- app/views/user_mailer/infringement_email.html.erb
- config/environments/development.rb
- config/environments/preproduction.rb
- config/environments/production.rb
Where
=====
* **Related Issue:** #42 
What
====
Make applicattion able to to send email from any environment.
How
===
Adding development, preproduction and production configuration.
We used secrets for preproduction and production environments.
> Mailer configuration

- app/views/devise/sessions/new.html.erb
- app/views/events/show.html.erb
- app/views/layouts/_header.html.erb
- app/views/visitors/show.html.erb
- config/locales/devise.es.yml
- spec/features/users/sign_in_spec.rb
What
====
- Add new links and styles to sign_in page
Screenshots
===========
Test
====
- Add missing specs
Deployment
==========
- As usual
Warnings
========
- None
> Check sign in

- app/helpers/admin/events_helper.rb
- app/views/events/_form.html.erb
What
====
- Display fullname organization. Fix after js validation.
Test
====
- None
Deployment
==========
- As usual
Warnings
========
- None
> Manager suggestions

- app/models/organization.rb
- app/models/organization_registered_lobby.rb
- app/models/registered_lobby.rb
- db/migrate/20171222163325_remove_organization_reference_from_registered_lobbies.rb
- db/migrate/20171222163720_create_organization_registered_lobbies.rb
- db/schema.rb
- spec/factories/organization_registered_lobbies.rb
- spec/factories/registered_lobbies.rb
Where
=====
* **Related PR's:** #209 
What
====
We have merge PR #209  with errors. This PR is for fixing master.
How
===
Add missing migration. Fix N-M relation between organizations and registered_lobby
> Fix registered lobby

- app/views/layouts/_footer.html.erb
- app/views/static_pages/websitemap.html.erb
- config/locales/public.en.yml
- config/locales/public.es.yml
- config/routes.rb
- spec/features/visitors/home_page_spec.rb
Where
=====
* **Related Issue:** #212 
What
====
- New static page with the website map
How
===
- Add a new static page
Screenshots
===========
Test
====
- Added the corresponding test
> add website map

- lib/tasks/events.rake
Where
=====
* **Related Issue:** #222 
Update status of existing events
- Update to status "accepted" if scheduled date is greater than today.
- Update to status "done" if scheduled date is less than today
Screenshots
===========
- None
Test
====
- None
Deployment
==========
- Execute rake events:update_old_event_status
Warnings
========
- None
> Add new task update old event status

- lib/tasks/events.rake
Where
=====
* **Related Issue:** #222 
What
====
Print some output to feedback the runner.
How
===
Adding some puts statements.
> Add output to events rake tasks

- app/assets/javascripts/events.js.erb
- app/helpers/events_helper.rb
- app/models/event.rb
- app/views/events/_participant_fields.html.erb
- app/views/layouts/_admin_sidebar.html.erb
- app/views/layouts/_header.html.erb
- spec/features/admin/events_spec.rb
What
====
- Fix suggestion by customer
Screenshots
===========
- None
Test
====
- Add missing specs
Deployment
==========
- As usual
Warnings
========
- None
> Pending suggestions

- lib/tasks/events.rake
Where
=====
* **Related Issue:** #222 
What
====
Avoid model validations on old events update.
How
===
Using update_attribute
> Skip model validations on old event update task

- lib/tasks/events.rake
Where
=====
* **Related Issue:** #222 
What
====
Add forgotten each in ruby loop. 😓
> Ooops! Add missing 'each' to loop code

- lib/tasks/events.rake
Where
=====
* **Related PR's:** #222
What
====
Set old events published_at to event.scheduled at date.
How
===
Updating attribute at rake task
> Set old events default published_at

- app/assets/javascripts/events.js.erb
- app/controllers/events_controller.rb
- app/views/events/_form.html.erb
- config/locales/admin.en.yml
- config/locales/admin.es.yml
- config/locales/en.yml
- config/locales/es.yml
- db/migrate/20171227235926_remove_accepted_reason_field_from_events.rb
- db/schema.rb
- lib/events_exporter.rb
- spec/features/admin/events_spec.rb
- spec/features/mailers/events_mailer_spec.rb
What
====
- Add status :accepted without accepted reasons 
How
===
- Remove accepted reasons validations
Screenshots
===========
- None
Test
====
- Fix spec
Deployment
==========
- Rake db:migrate
Warnings
========
- None
> Remove accepted reasons. Fix specs.

- app/controllers/admin/organizations_controller.rb
- app/mailers/application_mailer.rb
- app/mailers/event_mailer.rb
- app/mailers/organization_mailer.rb
- app/mailers/user_mailer.rb
- app/models/event.rb
- app/models/organization.rb
- app/views/admin/organizations/_data.html.erb
- app/views/areas/_form.html.erb
- app/views/event_mailer/cancel.html.erb
- app/views/event_mailer/create.html.erb
- spec/features/admin/organizations_spec.rb
- spec/features/mailers/events_mailer_spec.rb
- spec/features/mailers/organizations_mailer_spec.rb
- spec/mailers/user_mailer_spec.rb
What
====
- Check all emails
- Fix category id
- Change from by default
Screenshots
===========
- None
Test
====
- Fix specs
Deployment
==========
- As usual
Warnings
========
- Cancel email pending enhancement
> Check all emails.

- Gemfile
- Gemfile.lock
- config/initializers/rollbar.rb
- config/secrets.yml.example
What
====
- Configure Rollbar for exception notifications
How
===
- Adding rollbar gem
- Adding secret token placeholder
Screenshots
===========
- Test notification
Test
====
- No need
Deployment
==========
- Add token to secrets.yml in staging and production environments
Warnings
========
- None
> Configure Rollbar for exception notifications

- app/controllers/admin_controller.rb
- app/controllers/application_controller.rb
- app/controllers/events_controller.rb
- app/controllers/uweb_access_controller.rb
- app/views/events/_form.html.erb
- app/views/layouts/_admin_sidebar.html.erb
- lib/uweb_api.rb
What
====
Customers are experiencing problems in login through external application UWEB.
Checking UWEB related code i see a recent change on uweb_controller with an error. This controller was using an "@events_path" instance varible declared at admin_controller, the problem is uweb_controller does not inherits from admin_controller, it does from application_controller where this instance variable never exists.
How
===
Adding a method to get events_home_path by given user to application controller and making it accesible from views through helper_method at controller level.
> Uweb access

- app/controllers/events_controller.rb
- spec/features/admin/events_spec.rb
Where
=====
* **Related Issue:** #247 
What
====
- Display spectific events after sign_in with role User. 
How
===
- Specifying the parameters by default that you want to show after sign in.
Test
====
- Added the specific test
> Index issue with tagged event

- app/controllers/events_controller.rb
- app/helpers/events_helper.rb
- app/views/events/_form.html.erb
- spec/features/admin/events_spec.rb
What
====
- Fix redirect to index with correct params after sing in
- Fix disabled accept button after validation error
Screenshots
===========
- None
Test
====
- Fix specs.
Deployment
==========
- As usual
Warnings
========
- None
> Fix events

- app/controllers/positions_controller.rb
- spec/features/admin/events_spec.rb
What
====
- Fix position results on autocomplete when user is lobby.
How
===
- Add scope current to Position results.
Screenshots
===========
- None
Test
====
- Add missing spec
Deployment
==========
- As usual
Warnings
========
- None
> Fix autocomplete return values.

- app/assets/stylesheets/all.css.scss
Where
=====
* **Related Issue:** #253 
What
====
Remove specific protocol from imports statements.
> Remove https from google fonts imports and stringify url.

- app/views/users/show.html.erb
Where
=====
* **Related Issue:** #256 
What
====
Render manager holder position only when a current position already exists.
How
===
Adding presence condition.
> Render manager holder position only when a current position exists

- app/views/events/show.html.erb
What
====
Event attendees and participants are duplicated.
How
===
Removing duplicated data.
> Remove duplicated information from event show fo admins

- app/controllers/application_controller.rb
- app/controllers/events_controller.rb
- app/controllers/uweb_access_controller.rb
- app/views/events/_form.html.erb
- app/views/layouts/_admin_sidebar.html.erb
- spec/features/admin/events_spec.rb
What
====
- Redirect after save and create to correct index when user is a manager.
Screenshots
===========
- None
Test
====
- Add specs
Deployment
==========
- As usual
Warnings
========
- None
> Fix redirect after save and after create when user is a manager.

- app/models/attachment.rb
What
====
Allow users to upload CSV files
How
===
Adding CSV mime type to attachment model.
> Add text/csv content type to attachment allowed content types

- app/controllers/visitors_controller.rb
- app/models/event.rb
- config/locales/public.es.yml
- spec/features/visitors/event_page_spec.rb
What
====
- Only display events with status accepted or done with valid published_at
How
===
- Add filter searcher by status on visitors controller.
Screenshots
===========
- None
Test
====
- Fix specs
Deployment
==========
- As usual.
Warnings
========
- None
> Display events by status

- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/static-pages.scss
- app/views/organizations/_common_instructions_text.es.html.erb
- app/views/registration_lobbies/index.html.erb
- app/views/static_pages/code_of_conduct.html.erb
- config/routes.rb
What
====
Changes on static pages and external links.
> Some quick fixes

- app/assets/javascripts/admin/organizations.js
- app/controllers/admin/organizations_controller.rb
- app/views/admin/organizations/_lobby_data.html.erb
- app/views/admin/organizations/_represented_entities.html.erb
- app/views/admin/organizations/_represented_entities_fields.html.erb
- app/views/admin/organizations/show.html.erb
- app/views/organizations/show.html.erb
- config/locales/organizations.es.yml
- db/migrate/20180106204752_add_own_lobby_activity_and_foreign_lobby_activity_to_organizations.rb
- db/schema.rb
- spec/features/admin/organizations_spec.rb
What
====
- Add missing fields from Organization.
How
===
- Add own_lobby_activity and foreign_lobby_activity
Screenshots
===========
- None
Test
====
- Fix specs.
Deployment
==========
- Need migrate
Warnings
========
- None
> Add missing fields on organizations.

- app/views/visitors/show.html.erb
- spec/features/visitors/event_page_spec.rb
Where
=====
* **Related Issue:** https://github.com/AyuntamientoMadrid/agendas/issues/297
How
===
- I added a condition before rendering the event schedule
> added condition before render the event schedule

- app/helpers/admin/sidebar_helper.rb
- app/views/layouts/_admin_sidebar.html.erb
- spec/features/admin/events_spec.rb
Where
=====
* **Related Issue:** https://github.com/AyuntamientoMadrid/agendas/issues/300
What
====
- Changes hashes with strings as keys to hashes with symbols instead
> fix deprecation warning on test (hash with string keys)

- .gitignore
- README.md
- config/deploy.rb
- config/sunspot.yml.example
What
====
Delete explicit information from repository.
How
===
Removing solr connection secrets from application.
Add sunspot.yml configuration file to capistrano deployment linked_files to check remote file existence during deployments.
Screenshots
===========
Not needed
Test
====
Same
Deployment
==========
Check production and preproduction servers shared configuration files before deployment:
**PREPRODUCTION**
```
preproduction:
solr:
hostname: preproduction.server.name
port: xxx
log_level: INFO
path: /solr/core0
```
**PRODUCTION**
```
production:
solr:
hostname: production.server.name
port: xxx
log_level: INFO
path: /solr/core0
```
> Update solr configuration files
